language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
script: rake 

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/745964c70588b60bb4b1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
