@startuml
'-----------------------------------
' Interface graphique cours de Meyer
' JMB 2019
'-----------------------------------

@startsalt
{^"Flight Reservation"
  From: | ^Toulouse^ | [<b>H</b>elp<&info>]
  To:   | ^Paris   ^
  No earlier than: | "18/02/2019 <&calendar>"
  No later than: | "19/02/2019 <&calendar>"
  <&warning> <b>Error!</b> | <b> Choose a date in the future! </b>
[<b>R</b>eset] | [<b>B</b>ook a Seat <&account-login>] | [<b>C</b>ancel <&circle-x>]
}
@endsalt

@enduml
'-----------------------------------
