@startuml

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

@startuml

'-----------------------------------
' Standards Taxonomy (taken from Friedenthal 2016)
' JMB 2018
'-----------------------------------

' Default settings
'-----------------------------------
' left to right direction 'does not work for sequence diagrams :-(

@startsalt
{^"Flight Reservation"
  From: | ^Toulouse^ | [Help<&info>]
  To:   | ^Paris   ^
  No earlier than: | "18/02/2019 <&calendar>"
  No later than: | "19/02/2019 <&calendar>"
  <&warning> <b>Error!</b> | <b> Choose a date in the future! </b>
[Clear] | [Reserve a Seat <&account-login>] | [Cancel <&circle-x>]
}
@endsalt

@enduml
