@startuml archi

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

@startuml

'-----------------------------------
' Standards Taxonomy (taken from Friedenthal 2016)
' JMB 2018
'-----------------------------------

' Default settings
'-----------------------------------
' left to right direction 'does not work for sequence diagrams :-(
'hide circle
hide empty members
hide methods
' Colors & Fonts
'-----------------------------------
'Colors => see http://plantuml.com/color
'skinparam monochrome true
'skinparam monochrome reverse
'skinparam handwritten true
skinparam package {
	BackgroundColor empty
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName TrebuchetMS
}
skinparam roundcorner 10

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName TrebuchetMS
}
skinparam arrow {
    MessageAlign center
}

' Attribute and name values (for translation purpose).
'-----------------------------------

' Usefull functions
'-----------------------------------
!define objet(nom,type) class "<u>nom : type"

hide circle
hide empty members
hide empty methods


' package typing {
' 	interface Iterator
' }

' package "code" {
' class int
' class ListInt
' class Solution
' }
' ListInt -right--- "*" int
' Solution -- "*" ListInt

class Class {
	attribute : Type
}
package Types {
	class AnotherType
}
Class .> AnotherType : <<import>>\nType
@enduml
