@startuml

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

'hide circle
hide empty members
hide empty methods
'skinparam classAttributeIconSize 0

class Xorg {
{static} blob : Xorg
# Xorg()
{static} + getInstance() : Xorg
}

Xorg --> "blob" Xorg
note "if blob == null {\n  blob = new Xorg();\n}\nreturn blob;" as N
Xorg .. N

@enduml
